var N = null;var sourcesIndex = {};
sourcesIndex["arrayfire"] = {"name":"","dirs":[{"name":"algorithm","files":["mod.rs"]},{"name":"arith","files":["mod.rs"]},{"name":"blas","files":["mod.rs"]},{"name":"data","files":["mod.rs"]},{"name":"device","files":["mod.rs"]},{"name":"image","files":["mod.rs"]},{"name":"lapack","files":["mod.rs"]},{"name":"random","files":["mod.rs"]},{"name":"signal","files":["mod.rs"]},{"name":"sparse","files":["mod.rs"]},{"name":"statistics","files":["mod.rs"]},{"name":"vision","files":["mod.rs"]}],"files":["array.rs","backend.rs","defines.rs","dim4.rs","error.rs","graphics.rs","index.rs","lib.rs","macros.rs","num.rs","seq.rs","util.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"notbsd","dirs":[{"name":"linux","dirs":[{"name":"other","dirs":[{"name":"b64","files":["mod.rs","not_x32.rs","x86_64.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["dox.rs","lib.rs","macros.rs"]};
sourcesIndex["num"] = {"name":"","files":["lib.rs"]};
sourcesIndex["num_bigint"] = {"name":"","files":["algorithms.rs","bigint.rs","biguint.rs","lib.rs","macros.rs","monty.rs"]};
sourcesIndex["num_complex"] = {"name":"","files":["cast.rs","lib.rs","pow.rs"]};
sourcesIndex["num_integer"] = {"name":"","files":["lib.rs","roots.rs"]};
sourcesIndex["num_iter"] = {"name":"","files":["lib.rs"]};
sourcesIndex["num_rational"] = {"name":"","files":["lib.rs"]};
sourcesIndex["num_traits"] = {"name":"","dirs":[{"name":"ops","files":["checked.rs","inv.rs","mod.rs","mul_add.rs","saturating.rs","wrapping.rs"]}],"files":["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]};
createSourceSidebar();
