(function() {var implementors = {};
implementors['arrayfire'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.AfError.html' title='arrayfire::AfError'>AfError</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.Aftype.html' title='arrayfire::Aftype'>Aftype</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.InterpType.html' title='arrayfire::InterpType'>InterpType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.BorderType.html' title='arrayfire::BorderType'>BorderType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.Connectivity.html' title='arrayfire::Connectivity'>Connectivity</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.ConvMode.html' title='arrayfire::ConvMode'>ConvMode</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.ConvDomain.html' title='arrayfire::ConvDomain'>ConvDomain</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.MatchType.html' title='arrayfire::MatchType'>MatchType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.ColorSpace.html' title='arrayfire::ColorSpace'>ColorSpace</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.MatProp.html' title='arrayfire::MatProp'>MatProp</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.NormType.html' title='arrayfire::NormType'>NormType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='arrayfire/enum.ColorMap.html' title='arrayfire::ColorMap'>ColorMap</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='arrayfire/struct.Dim4.html' title='arrayfire::Dim4'>Dim4</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
